### ISSUE TITLE
fsevent support

### ISSUE THREAD

**Issue by octplane** [passcod/rsnotify#7]
Hi,

I'm the maintainer of a minimal but working [fsevent](https://github.com/octplane/fsevent-rust) binding for OSX. I guess we could try to integrate the two together, if this is possible :)

I think I should have a look at the inotify watcher in order to have something that blends in your library correctly. Let me know if there are some pitfalls I should be prepared to face... If you are interested in this, I can start digging :)

**Comment by Centril** [comment]
Hi @octplane

I think it is a good idea to let [fsevent](https://github.com/octplane/fsevent-rust) stand on its own and then use it as a dependency in `rsnotify` or the cross platform library.

I'm also working on a `fsnotify` library: https://github.com/Lumenix/rust-fsnotify
We might "merge" this repo and that one together...

Join `#rust-fsnotify @ irc.mozilla.org` for more direct discussion on how to merge stuff together...

**Comment by passcod** [comment]
@octplane As @Centril said, currently the way I've done things for this repo is to create an implementation of the Watcher for [platform] using bindings as dependencies... but I'm thinking of changing this, notably because _rsnotify_ currently always has to lag behind its _inotify_ dependency. Merging the bindings directly into the library, creating something with zero non-system dependencies, is tempting.

@Centril I haven't yet decided whether I want to merge or not.

@octplane The main difference between a binding and a Watcher is that these have a runtime, i.e. they run a loop and pump out events on a channel. Something I've done in the current Watchers is use `RwLock`s to synchronise state, but that may be over-complex... if you find a better way, don't hesitate to implement it :)

Something to note is that currently _rsnotify_ does recursive watches (observes the path and all subfolders), while IIRC `fsevents` (like many other system notifiers) doesn't, so you need to handle the recursiveness in the Watcher.

If I haven't discouraged you yet, I am definitely interested! :)

**Comment by octplane** [comment]
Hello,

I'm not discouraged :) I just need to find starting point...

Note that: my fsevent binding has to run in its own loop and I'm doing recursive watch by default because it's much easier to do with the cocoa API.

I'll join on irc, to immerge myself on your spirit :-D

**Comment by passcod** [comment]
> my fsevent binding has to run in its own loop and I'm doing recursive watch by default

well that's about everything taken care of then ;)

**Comment by blaenk** [comment]
Hey @octplane any news on this? It would be awesome if you went ahead and added OS X support to this package! I'd give it a shot but I don't have access to OS X.

**Comment by octplane** [comment]
Yep, I started looking again at this yesterday. I hope to be able to get some time push something soon...
